Movement
FRC1076/WAPUR2018 pull request #75
Opened 2017-12-03 23:41 UTC by helenaheinonen

Add the basic autonomous stuff

2017-12-04 02:30 UTC, porglezomp requested changes

2017-12-04 02:30 UTC, porglezomp commented on robot.py
> +class DriveTrain:
Question for people, what is this code for? (The `DriveTrain` and `DriveControl` classes.) Is this just from following the tutorial? Do we need it?

2017-12-04 02:30 UTC, porglezomp commented on robot.py
> +    def forwardCommand(speed, time):
I don't understand this `forwardCommand` function

2017-12-08 20:39 UTC, Dannihu01 approved these changes

2017-12-09 00:27 UTC, porglezomp approved these changes

2017-12-09 00:27 UTC, porglezomp commented
Okay, looks good now. It's building…

2017-12-09 00:29 UTC, merged